<?php

function pingpong_menu() {
    $items = array();
    $items['ping_pong'] = array(
        'title' => 'Ping Pong',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('pingpong_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['ping_pong_success_page'] = array(
        'title' => 'Success',
        'page callback' => 'pingpong_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function pingpong_form() {
    $form['count_goal'] = array(
        '#title' => 'Count Goal',
        '#type' => 'textfield',
        '#description' => t('Please enter a number to count up to.'),
        '#element_validate' => array('element_validate_integer_positive', 'element_validate_range', 'element_validate_odd'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );

    return $form;
}

function element_validate_odd($element) {
  if ($element['#value'] % 2 == 0) {
      form_error($element, t('Number needs to be odd.'));
  }
}

function element_validate_range($element) {
    if ($element['#value'] > 50 || $element['#value'] < 10) {
        form_error($element, t('Number needs to be less than 50 or greater than 10.'));
    }
}

function pingpong_form_submit($form, &$form_state) {
    $count_max = $form_state['values']['count_goal'];
    $pingpong_output = array();

    for ($i=1; $i <= $count_max; $i++) {
        if ($i % 3 == 0 && $i %5 == 0) {
            array_push($pingpong_output, "ping-pong");
        } elseif ($i % 3 == 0) {
            array_push($pingpong_output, "ping");
        } elseif ($i % 5 == 0) {
            array_push($pingpong_output, "pong");
        } else {
            array_push($pingpong_output, $i);
        }
    }

    $_SESSION['ping_pong_output'] = $pingpong_output;
    $form_state['redirect'] = 'ping_pong_success_page';
}

function pingpong_success() {
    $output = '<ul>';
    foreach ($_SESSION['ping_pong_output'] as $value) {
        $output = $output . '<li>' . $value . '</li>';
    }
    $output = $output . '</ul>';
    return "Hooray! $output";
}
