<?php

function title_case_menu() {
  $items = array();

  $items['title_case'] = array(
      'title' => 'Title Case',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('title_case_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
  );

  $items['title_case_success_page'] = array(
      'title' => 'Success',
      'page callback' => 'title_case_success',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
  );
  return $items;
}

function title_case_form() {
  $form['sentence'] = array(
      '#title' => 'Sentence',
      '#type' => 'textfield',
      '#description' => t('Please enter a sentence.'),
  );

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Return Sentence',
  );
  return $form;
}

function title_case_form_submit($form, &$form_state) {
    $input = $form_state['values']['sentence'];
    var_dump($input);
    $_SESSION['output'] = ucwords($input);
    $form_state['redirect'] = 'title_case_success_page';
}

function title_case_success() {
    $output = $_SESSION['output'];
    return "Here is your sentence: " . $output;
}
